BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `books` (
	`title_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT,
	`pages`	INTEGER
);
CREATE TABLE IF NOT EXISTS `authors` (
	`author_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title_id`	INTEGER NOT NULL,
	`author`	TEXT DEFAULT 125
);
COMMIT;
